apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PolicyStrictOnly
metadata:
  name: policy-strict-constraint
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["authentication.istio.io"]
        kinds: ["Policy"]
    namespaces: ["default"]
